"""empty message

Revision ID: 1df175fa1872
Revises: 4d803d68b58a
Create Date: 2018-05-17 14:25:40.326115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df175fa1872'
down_revision = '4d803d68b58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dispatch_time', sa.BigInteger(), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('start_sn', sa.BigInteger(), nullable=True),
    sa.Column('end_sn', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dispatch_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('start_sn', sa.BigInteger(), nullable=True),
    sa.Column('end_sn', sa.BigInteger(), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'qrcode', sa.Column('dispatch_id', sa.BigInteger(), nullable=True))
    op.add_column(u'qrcode', sa.Column('product_info_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'qrcode', 'product_info_id')
    op.drop_column(u'qrcode', 'dispatch_id')
    op.drop_table('product_info')
    op.drop_table('dispatch')
    # ### end Alembic commands ###
