"""empty message

Revision ID: 4568db09ea80
Revises: 
Create Date: 2018-04-16 10:52:11.320201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4568db09ea80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('product_place', sa.String(length=128), nullable=True),
    sa.Column('customs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apply',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('apply_time', sa.BigInteger(), nullable=True),
    sa.Column('dispathc_time', sa.BigInteger(), nullable=True),
    sa.Column('apply_sn', sa.String(length=32), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('start_sn', sa.BigInteger(), nullable=True),
    sa.Column('end_sn', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('others', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categroy',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('paraent_name', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('create_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('history_sn', sa.BigInteger(), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=True),
    sa.Column('start_sn', sa.BigInteger(), nullable=True),
    sa.Column('end_sn', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qrcode',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sn', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.VARBINARY(length=64), nullable=True),
    sa.Column('history_sn', sa.BigInteger(), nullable=True),
    sa.Column('apply_sn', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('sn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qrcode')
    op.drop_table('merchant')
    op.drop_table('create_history')
    op.drop_table('categroy')
    op.drop_table('apply')
    op.drop_table('agent')
    # ### end Alembic commands ###
