"""empty message

Revision ID: 4d803d68b58a
Revises: 4568db09ea80
Create Date: 2018-04-16 16:25:31.579297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d803d68b58a'
down_revision = '4568db09ea80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'level')
    # ### end Alembic commands ###
