"""empty message

Revision ID: 015f748b96cb
Revises: e0fdb6d0d20a
Create Date: 2017-08-29 16:15:39.907192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015f748b96cb'
down_revision = 'e0fdb6d0d20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_history', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_history', 'status')
    # ### end Alembic commands ###
