"""empty message

Revision ID: 0dd6aa2bec74
Revises: 15a411941985
Create Date: 2017-07-07 14:55:00.360068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd6aa2bec74'
down_revision = '15a411941985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('deal_sn', sa.String(length=64), nullable=True),
    sa.Column('poster_id', sa.BigInteger(), nullable=True),
    sa.Column('post_time', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('imgs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_article_id'), 'article', ['article_id'], unique=True)
    op.create_index(op.f('ix_article_store_id'), 'article', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_store_id'), table_name='article')
    op.drop_index(op.f('ix_article_article_id'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
