"""empty message

Revision ID: 15a411941985
Revises: c5d6958f8074
Create Date: 2017-07-07 11:13:21.306557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a411941985'
down_revision = 'c5d6958f8074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_store',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_store_store_id'), 'favorite_store', ['store_id'], unique=False)
    op.create_index(op.f('ix_favorite_store_user_id'), 'favorite_store', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_store_user_id'), table_name='favorite_store')
    op.drop_index(op.f('ix_favorite_store_store_id'), table_name='favorite_store')
    op.drop_table('favorite_store')
    # ### end Alembic commands ###
