"""empty message

Revision ID: 1cb39bd2a3a6
Revises: 50fa614a59a0
Create Date: 2017-11-16 17:48:43.771810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb39bd2a3a6'
down_revision = '50fa614a59a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lottery', sa.Column('lottery_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lottery', 'lottery_type')
    # ### end Alembic commands ###
