"""empty message

Revision ID: 218e5e5cd633
Revises: 
Create Date: 2017-07-05 13:59:47.596178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218e5e5cd633'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('banner_id', sa.BigInteger(), nullable=True),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_banner_id'), 'banner', ['banner_id'], unique=False)
    op.create_table('hot_category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('img', sa.String(length=256), nullable=True),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('stores', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hot_category_category'), 'hot_category', ['category'], unique=True)
    op.create_table('id_box',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('store',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('lng', sa.DECIMAL(precision=13, scale=10), nullable=True),
    sa.Column('lat', sa.DECIMAL(precision=13, scale=10), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('per', sa.Integer(), nullable=True),
    sa.Column('comment_amount', sa.Integer(), nullable=True),
    sa.Column('favorites_amount', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('open_time', sa.Integer(), nullable=True),
    sa.Column('close_time', sa.Integer(), nullable=True),
    sa.Column('set_up', sa.BigInteger(), nullable=True),
    sa.Column('banners_list', sa.JSON(), nullable=True),
    sa.Column('menus_list', sa.JSON(), nullable=True),
    sa.Column('services', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('token_time', sa.BigInteger(), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('register_time', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    op.create_table('device',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sn', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('install_time', sa.BigInteger(), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_sn'), 'device', ['sn'], unique=True)
    op.create_table('deal',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sn', sa.String(length=64), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('device_sn', sa.String(length=32), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('items_list', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_sn'], ['device.sn'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_device_sn'), 'deal', ['device_sn'], unique=False)
    op.create_index(op.f('ix_deal_sn'), 'deal', ['sn'], unique=True)
    op.create_index(op.f('ix_deal_time'), 'deal', ['time'], unique=False)
    op.create_table('seedtoken',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('enable_time', sa.BigInteger(), nullable=True),
    sa.Column('device_sn', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['device_sn'], ['device.sn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seedtoken')
    op.drop_index(op.f('ix_deal_time'), table_name='deal')
    op.drop_index(op.f('ix_deal_sn'), table_name='deal')
    op.drop_index(op.f('ix_deal_device_sn'), table_name='deal')
    op.drop_table('deal')
    op.drop_index(op.f('ix_device_sn'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('store')
    op.drop_table('id_box')
    op.drop_index(op.f('ix_hot_category_category'), table_name='hot_category')
    op.drop_table('hot_category')
    op.drop_index(op.f('ix_banner_banner_id'), table_name='banner')
    op.drop_table('banner')
    # ### end Alembic commands ###
