"""empty message

Revision ID: 2fe75874420d
Revises: 8ac882759e35
Create Date: 2017-07-12 14:49:46.035606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe75874420d'
down_revision = '8ac882759e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('setting_time', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'setting_time')
    # ### end Alembic commands ###
