"""empty message

Revision ID: 320664d19dfa
Revises: beffc16f85c4
Create Date: 2017-11-06 14:39:57.544722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320664d19dfa'
down_revision = 'beffc16f85c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'deal_ibfk_2', 'deal', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'deal_ibfk_2', 'deal', 'store', ['store_id'], ['store_id'])
    # ### end Alembic commands ###
