"""empty message

Revision ID: 3281f41376ce
Revises: 564ddc593e33
Create Date: 2017-08-24 14:10:08.955182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3281f41376ce'
down_revision = '564ddc593e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('orgin_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'orgin_id')
    # ### end Alembic commands ###
