"""empty message

Revision ID: 4b77cf02a9c7
Revises: 2fe75874420d
Create Date: 2017-07-12 16:48:21.310918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b77cf02a9c7'
down_revision = '2fe75874420d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('app_print_baudrate', sa.String(length=32), nullable=True))
    op.add_column('device', sa.Column('app_received_baudrate', sa.String(length=32), nullable=True))
    op.add_column('device', sa.Column('app_version', sa.String(length=32), nullable=True))
    op.add_column('device', sa.Column('newest_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'newest_url')
    op.drop_column('device', 'app_version')
    op.drop_column('device', 'app_received_baudrate')
    op.drop_column('device', 'app_print_baudrate')
    # ### end Alembic commands ###
