"""empty message

Revision ID: 4e7c54670fb8
Revises: c3a67802226b
Create Date: 2017-10-24 09:51:36.931025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7c54670fb8'
down_revision = 'c3a67802226b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deal_sn', sa.String(length=64), nullable=True),
    sa.Column('device_sn', sa.String(length=32), nullable=True),
    sa.Column('receive_time', sa.BigInteger(), nullable=True),
    sa.Column('convert_time', sa.BigInteger(), nullable=True),
    sa.Column('deal_type', sa.Integer(), nullable=True),
    sa.Column('deal_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_status_deal_sn'), 'deal_status', ['deal_sn'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_status_deal_sn'), table_name='deal_status')
    op.drop_table('deal_status')
    # ### end Alembic commands ###
