"""empty message

Revision ID: 4eb67ab19f92
Revises: e209767b8014
Create Date: 2017-07-28 17:56:41.796161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb67ab19f92'
down_revision = 'e209767b8014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('register_time', sa.BigInteger(), nullable=True),
    sa.Column('last_login_time', sa.BigInteger(), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'article', sa.Column('region_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'article', 'region_code')
    op.drop_table('web_user')
    # ### end Alembic commands ###
