"""empty message

Revision ID: 50fa614a59a0
Revises: 76b8218ec467
Create Date: 2017-11-16 17:21:41.100352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fa614a59a0'
down_revision = '76b8218ec467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lottery', sa.Column('lottery_info', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lottery', 'lottery_info')
    # ### end Alembic commands ###
