"""empty message

Revision ID: 564ddc593e33
Revises: bcd1664cb1e9
Create Date: 2017-08-23 17:15:00.067883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564ddc593e33'
down_revision = 'bcd1664cb1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('orgin', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'orgin')
    # ### end Alembic commands ###
