"""empty message

Revision ID: 5689ebb11034
Revises: 6c7131d31405
Create Date: 2017-11-14 15:06:03.228757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5689ebb11034'
down_revision = '6c7131d31405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_status', sa.Column('deal_time', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal_status', 'deal_time')
    # ### end Alembic commands ###
