"""empty message

Revision ID: 5b84b38f5a79
Revises: bbc2c6833fe4
Create Date: 2017-07-13 14:48:13.393421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b84b38f5a79'
down_revision = 'bbc2c6833fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('time', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'time')
    # ### end Alembic commands ###
