"""empty message

Revision ID: 6b275d5cc28c
Revises: ca0add423e34
Create Date: 2017-07-06 10:42:48.954641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b275d5cc28c'
down_revision = 'ca0add423e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=64), nullable=True))
    op.drop_column('user', 'token')
    op.drop_column('user', 'token_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('token', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'city')
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###
