"""empty message

Revision ID: 730a4d89b050
Revises: 5b84b38f5a79
Create Date: 2017-07-14 11:27:47.296025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '730a4d89b050'
down_revision = '5b84b38f5a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('capture_baudrate', sa.String(length=32), nullable=True))
    op.add_column('device', sa.Column('local_setting_version', sa.BigInteger(), nullable=False))
    op.add_column('device', sa.Column('newest_setting_version', sa.BigInteger(), nullable=False))
    op.drop_column('device', 'baud_rate')
    op.drop_column('device', 'setting_time')
    op.drop_column('device', 'local_setting_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('local_setting_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.add_column('device', sa.Column('setting_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.add_column('device', sa.Column('baud_rate', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('device', 'newest_setting_version')
    op.drop_column('device', 'local_setting_version')
    op.drop_column('device', 'capture_baudrate')
    # ### end Alembic commands ###
