"""empty message

Revision ID: 76b8218ec467
Revises: 7c4c7a3aae40
Create Date: 2017-11-15 14:52:37.910277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76b8218ec467'
down_revision = '7c4c7a3aae40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hot_category', 'store_id')
    op.add_column('store', sa.Column('special_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'special_type')
    op.add_column('hot_category', sa.Column('store_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
