"""empty message

Revision ID: 7c4c7a3aae40
Revises: 5689ebb11034
Create Date: 2017-11-15 14:35:44.436159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c4c7a3aae40'
down_revision = '5689ebb11034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hot_category', sa.Column('category_img', sa.String(length=256), nullable=True))
    op.add_column('hot_category', sa.Column('store_id', sa.BigInteger(), nullable=True))
    op.drop_index('ix_hot_category_category', table_name='hot_category')
    op.create_index(op.f('ix_hot_category_category'), 'hot_category', ['category'], unique=False)
    op.drop_column('hot_category', 'stores')
    op.drop_column('hot_category', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hot_category', sa.Column('img', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('hot_category', sa.Column('stores', mysql.VARCHAR(length=512), nullable=True))
    op.drop_index(op.f('ix_hot_category_category'), table_name='hot_category')
    op.create_index('ix_hot_category_category', 'hot_category', ['category'], unique=True)
    op.drop_column('hot_category', 'store_id')
    op.drop_column('hot_category', 'category_img')
    # ### end Alembic commands ###
