"""empty message

Revision ID: 8ac882759e35
Revises: afb68ea27994
Create Date: 2017-07-12 10:18:40.317954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac882759e35'
down_revision = 'afb68ea27994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('baud_rate', sa.String(length=32), nullable=True))
    op.add_column('device', sa.Column('bluetooth_white_list', sa.JSON(), nullable=True))
    op.add_column('device', sa.Column('ip_white_list', sa.JSON(), nullable=True))
    op.add_column('device', sa.Column('net_port', sa.String(length=32), nullable=True))
    op.add_column('device', sa.Column('problem', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('wifi_encrypt_type', sa.String(length=32), nullable=True))
    op.add_column('device', sa.Column('wifi_name', sa.String(length=64), nullable=True))
    op.add_column('device', sa.Column('wifi_password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'wifi_password')
    op.drop_column('device', 'wifi_name')
    op.drop_column('device', 'wifi_encrypt_type')
    op.drop_column('device', 'problem')
    op.drop_column('device', 'net_port')
    op.drop_column('device', 'ip_white_list')
    op.drop_column('device', 'bluetooth_white_list')
    op.drop_column('device', 'baud_rate')
    # ### end Alembic commands ###
