"""empty message

Revision ID: 8e86b72d8dfb
Revises: 9e753e292249
Create Date: 2017-08-22 13:46:05.144152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e86b72d8dfb'
down_revision = '9e753e292249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('tax', sa.Integer(), nullable=True))
    op.add_column('store', sa.Column('region', sa.String(length=64), nullable=True))
    op.add_column('store', sa.Column('store_sn', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'store_sn')
    op.drop_column('store', 'region')
    op.drop_column('deal', 'tax')
    # ### end Alembic commands ###
