"""empty message

Revision ID: 941f7a594fbd
Revises: 9e7e3e1afe07
Create Date: 2017-10-25 15:30:14.210647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941f7a594fbd'
down_revision = '9e7e3e1afe07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_paper',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_sn', sa.String(length=64), nullable=True),
    sa.Column('device_sn', sa.String(length=32), nullable=True),
    sa.Column('order_time', sa.BigInteger(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('tax', sa.Integer(), nullable=True),
    sa.Column('remark', sa.TEXT(), nullable=True),
    sa.Column('original_text', sa.TEXT(), nullable=True),
    sa.Column('original_id', sa.String(length=64), nullable=True),
    sa.Column('items_list', sa.JSON(), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('store_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_paper_device_sn'), 'order_paper', ['device_sn'], unique=False)
    op.create_index(op.f('ix_order_paper_order_sn'), 'order_paper', ['order_sn'], unique=True)
    op.create_index(op.f('ix_order_paper_order_time'), 'order_paper', ['order_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_paper_order_time'), table_name='order_paper')
    op.drop_index(op.f('ix_order_paper_order_sn'), table_name='order_paper')
    op.drop_index(op.f('ix_order_paper_device_sn'), table_name='order_paper')
    op.drop_table('order_paper')
    # ### end Alembic commands ###
