"""empty message

Revision ID: 9be2c41f289c
Revises: 0dd6aa2bec74
Create Date: 2017-07-07 16:09:46.891590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be2c41f289c'
down_revision = '0dd6aa2bec74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('per', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'per')
    # ### end Alembic commands ###
