"""empty message

Revision ID: 9d8345d01ec5
Revises: a385d8cc682a
Create Date: 2017-08-03 14:50:55.746137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8345d01ec5'
down_revision = 'a385d8cc682a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_state', sa.String(length=32), nullable=True))
    op.add_column('device', sa.Column('network_state', sa.String(length=32), nullable=True))
    op.add_column('device', sa.Column('port_connecting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'port_connecting')
    op.drop_column('device', 'network_state')
    op.drop_column('device', 'device_state')
    # ### end Alembic commands ###
