"""empty message

Revision ID: 9e7e3e1afe07
Revises: 200a46ee8552
Create Date: 2017-10-25 12:06:01.910592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7e3e1afe07'
down_revision = '200a46ee8552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_status', sa.Column('remark', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal_status', 'remark')
    # ### end Alembic commands ###
