"""empty message

Revision ID: a385d8cc682a
Revises: 4eb67ab19f92
Create Date: 2017-08-01 18:45:16.220072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a385d8cc682a'
down_revision = '4eb67ab19f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('wifi_list', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'wifi_list')
    # ### end Alembic commands ###
