"""empty message

Revision ID: ac453b2c26c1
Revises: 941f7a594fbd
Create Date: 2017-10-30 16:32:39.014280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac453b2c26c1'
down_revision = '941f7a594fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('qr_remark', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'qr_remark')
    # ### end Alembic commands ###
