"""empty message

Revision ID: afb68ea27994
Revises: d7d277e0fb06
Create Date: 2017-07-11 13:35:14.174880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb68ea27994'
down_revision = 'd7d277e0fb06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_article',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('article_id', sa.BigInteger(), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_article_article_id'), 'favorite_article', ['article_id'], unique=False)
    op.create_index(op.f('ix_favorite_article_user_id'), 'favorite_article', ['user_id'], unique=False)
    op.create_table('like_article',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('article_id', sa.BigInteger(), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_like_article_article_id'), 'like_article', ['article_id'], unique=False)
    op.create_index(op.f('ix_like_article_user_id'), 'like_article', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_like_article_user_id'), table_name='like_article')
    op.drop_index(op.f('ix_like_article_article_id'), table_name='like_article')
    op.drop_table('like_article')
    op.drop_index(op.f('ix_favorite_article_user_id'), table_name='favorite_article')
    op.drop_index(op.f('ix_favorite_article_article_id'), table_name='favorite_article')
    op.drop_table('favorite_article')
    # ### end Alembic commands ###
