"""empty message

Revision ID: bbc2c6833fe4
Revises: 4b77cf02a9c7
Create Date: 2017-07-12 17:48:14.062976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc2c6833fe4'
down_revision = '4b77cf02a9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('local_setting_time', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'local_setting_time')
    # ### end Alembic commands ###
