"""empty message

Revision ID: bcd1664cb1e9
Revises: 8e86b72d8dfb
Create Date: 2017-08-23 16:14:03.343663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd1664cb1e9'
down_revision = '8e86b72d8dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offline_histroy',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_sn', sa.String(length=32), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('store_name', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offline_histroy')
    # ### end Alembic commands ###
