"""empty message

Revision ID: beffc16f85c4
Revises: ac453b2c26c1
Create Date: 2017-10-31 18:14:10.611045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beffc16f85c4'
down_revision = 'ac453b2c26c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_store',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_sn', sa.String(length=32), nullable=True),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('store_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_sn')
    )
    op.drop_constraint(u'device_ibfk_1', 'device', type_='foreignkey')
    op.drop_column(u'device', 'store_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'device', sa.Column('store_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.create_foreign_key(u'device_ibfk_1', 'device', 'store', ['store_id'], ['store_id'])
    op.drop_table('device_store')
    # ### end Alembic commands ###
