"""empty message

Revision ID: c3a67802226b
Revises: a91ee7749540
Create Date: 2017-09-22 14:21:16.448885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a67802226b'
down_revision = 'a91ee7749540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_key',
    sa.Column('device_sn', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('device_sn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_key')
    # ### end Alembic commands ###
