"""empty message

Revision ID: c5d6958f8074
Revises: 6b275d5cc28c
Create Date: 2017-07-07 10:42:42.183548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d6958f8074'
down_revision = '6b275d5cc28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_time', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_time')
    # ### end Alembic commands ###
