"""empty message

Revision ID: ca0add423e34
Revises: 218e5e5cd633
Create Date: 2017-07-05 18:13:06.881922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0add423e34'
down_revision = '218e5e5cd633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('cuisines', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'cuisines')
    # ### end Alembic commands ###
