"""empty message

Revision ID: d7d277e0fb06
Revises: ae47947f90dd
Create Date: 2017-07-11 10:17:43.199971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d277e0fb06'
down_revision = 'ae47947f90dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('essence', sa.Boolean(), nullable=True))
    op.add_column('article', sa.Column('img_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'img_count')
    op.drop_column('article', 'essence')
    # ### end Alembic commands ###
