"""empty message

Revision ID: dd6d2f80981c
Revises: 3281f41376ce
Create Date: 2017-08-25 16:27:04.122864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6d2f80981c'
down_revision = '3281f41376ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('logo_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'logo_url')
    # ### end Alembic commands ###
