"""empty message

Revision ID: e209767b8014
Revises: ef95eb68a060
Create Date: 2017-07-18 13:35:32.162629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e209767b8014'
down_revision = 'ef95eb68a060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('total_device', sa.Integer(), nullable=True),
    sa.Column('online_device', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_time'), 'daily', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_time'), table_name='daily')
    op.drop_table('daily')
    # ### end Alembic commands ###
