"""empty message

Revision ID: e2672a6f3435
Revises: 015f748b96cb
Create Date: 2017-09-04 11:28:54.630190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2672a6f3435'
down_revision = '015f748b96cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('add_qr', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('order_invalid_keys', sa.JSON(), nullable=True))
    op.add_column('device', sa.Column('order_valid_keys', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'order_valid_keys')
    op.drop_column('device', 'order_invalid_keys')
    op.drop_column('device', 'add_qr')
    # ### end Alembic commands ###
