"""empty message

Revision ID: e55ea1c6732b
Revises: 1cb39bd2a3a6
Create Date: 2017-11-17 17:49:09.260969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55ea1c6732b'
down_revision = '1cb39bd2a3a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
