"""empty message

Revision ID: f160dc039a48
Revises: dd6d2f80981c
Create Date: 2017-08-25 17:18:51.284193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f160dc039a48'
down_revision = 'dd6d2f80981c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('logo_new', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('logo_urls', sa.JSON(), nullable=True))
    op.drop_column('device', 'logo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('logo_url', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('device', 'logo_urls')
    op.drop_column('device', 'logo_new')
    # ### end Alembic commands ###
