"""empty message

Revision ID: f776f7bb173a
Revises: 9be2c41f289c
Create Date: 2017-07-07 16:26:04.496471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f776f7bb173a'
down_revision = '9be2c41f289c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'anonymous')
    # ### end Alembic commands ###
